{{- if and .Values.ui.enabled .Values.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aerospike-ce-operator.ui.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerospike-ce-operator.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
