{{- if .Values.defaultTemplates.enabled }}
{{- range $name, $spec := .Values.defaultTemplates.templates }}
---
apiVersion: acko.io/v1alpha1
kind: AerospikeClusterTemplate
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-ce-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cluster-template
spec:
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
