apiVersion: acko.io/v1alpha1
kind: AerospikeCECluster
metadata:
  name: aerospike-ce-multirack
  namespace: aerospike
spec:
  size: 6
  image: aerospike:ce-8.1.1.1

  rackConfig:
    namespaces:
      - testns
    racks:
      - id: 1
      - id: 2
      - id: 3

  podSpec:
    aerospikeContainer:
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"

  storage:
    volumes:
      - name: data-vol
        source:
          persistentVolume:
            storageClass: standard
            size: 5Gi
        aerospike:
          path: /opt/aerospike/data
        cascadeDelete: false

  aerospikeConfig:
    service:
      cluster-name: aerospike-ce-multirack
      proto-fd-max: 15000

    network:
      service:
        address: any
        port: 3000
      heartbeat:
        mode: mesh
        port: 3002
      fabric:
        address: any
        port: 3001

    namespaces:
      - name: testns
        replication-factor: 2
        storage-engine:
          type: device
          file: /opt/aerospike/data/testns.dat
          filesize: 4294967296
