#!/usr/bin/env bash
# Generate API reference documentation from Go types using elastic/crd-ref-docs.
#
# Prerequisites:
#   go install github.com/elastic/crd-ref-docs@latest
#
# Usage:
#   bash docs/scripts/generate-api-reference.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOCS_DIR="${REPO_ROOT}/docs"
OUTPUT_FILE="${DOCS_DIR}/content/api-reference/aerospikececluster.md"
CONFIG_FILE="${DOCS_DIR}/crd-ref-docs-config.yaml"
SOURCE_PATH="${REPO_ROOT}/api/v1alpha1"

# Check if crd-ref-docs is installed
if ! command -v crd-ref-docs &>/dev/null; then
  echo "crd-ref-docs not found. Installing..."
  go install github.com/elastic/crd-ref-docs@latest
fi

TEMP_FILE=$(mktemp)
trap 'rm -f "${TEMP_FILE}"' EXIT

echo "Generating API reference from ${SOURCE_PATH}..."

crd-ref-docs \
  --source-path="${SOURCE_PATH}" \
  --config="${CONFIG_FILE}" \
  --renderer=markdown \
  --output-path="${TEMP_FILE}" \
  --max-depth=10

# Prepend Docusaurus frontmatter
cat > "${OUTPUT_FILE}" <<'FRONTMATTER'
---
sidebar_position: 1
title: AerospikeCECluster API Reference
---

<!-- This file is auto-generated by crd-ref-docs. Do not edit manually. -->
<!-- Regenerate with: make docs-generate-api -->

FRONTMATTER

cat "${TEMP_FILE}" >> "${OUTPUT_FILE}"

echo "API reference generated: ${OUTPUT_FILE}"
