{{- if and .Values.ui.enabled .Values.ui.rbac.create .Values.ui.k8s.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acko.ui.fullname" . }}
  labels:
    {{- include "acko.ui.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acko.ui.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acko.ui.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
