{{- if .Values.defaultTemplates.enabled }}
{{- range $name, $spec := .Values.defaultTemplates.templates }}
---
apiVersion: acko.io/v1alpha1
kind: AerospikeClusterTemplate
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-ce-kubernetes-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cluster-template
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
