{{- if and .Values.ui.enabled .Values.ui.rbac.create .Values.ui.k8s.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aerospike-ce-kubernetes-operator.ui.fullname" . }}
  labels:
    {{- include "aerospike-ce-kubernetes-operator.ui.labels" . | nindent 4 }}
rules:
  - apiGroups: ["acko.io"]
    resources: ["aerospikeclusters"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["acko.io"]
    resources: ["aerospikeclusters/status"]
    verbs: ["get"]
  - apiGroups: ["acko.io"]
    resources: ["aerospikeclustertemplates"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["acko.io"]
    resources: ["aerospikeclustertemplates/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
{{- end }}
