{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aerospike-ce-kubernetes-operator.ui.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerospike-ce-kubernetes-operator.ui.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.ui.env.corsOrigins | quote }}
  LOG_LEVEL: {{ .Values.ui.env.logLevel | quote }}
  K8S_MANAGEMENT_ENABLED: {{ .Values.ui.k8s.enabled | quote }}
  BACKEND_URL: "http://localhost:{{ .Values.ui.service.backendPort }}"
{{- end }}
