name: Lint

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'config/samples/**'
      - 'tokei.toml'
      - '.tokeignore'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/docs.yaml'
      - '.github/workflows/publish-chart.yml'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'config/samples/**'
      - 'tokei.toml'
      - '.tokeignore'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/docs.yaml'
      - '.github/workflows/publish-chart.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        run: make lint
