name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'config/samples/**'
      - 'tokei.toml'
      - '.tokeignore'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/docs.yaml'
      - '.github/workflows/publish-chart.yml'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'config/samples/**'
      - 'tokei.toml'
      - '.tokeignore'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/docs.yaml'
      - '.github/workflows/publish-chart.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Running unit tests
        run: make test-unit

  integration-test:
    name: Integration Tests (envtest)
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running integration tests
        run: make test-integration
